# -*- coding: utf-8 -*-
project   = "benchmarker"
release   = "0.1.0"
copyright = "copyright(c) 2010-2011 kuwata-lab.com all rights reserved"
license   = "Public Domain"

require 'fileutils'
include FileUtils

require 'rake/clean'
CLEAN.include("build/#{project}-#{release}")
CLOBBER.include("build")


task :default => :test

def _do_test
  Dir.glob('test/*_test.rb').each do |fname|
    sh "ruby #{fname}"
  end
end

desc "do test"
task :test do
  _do_test()
end

desc "do test for 1.8.6, 1.8.7, and 1.9.2"
task :test_all do
  orig_path = ENV['PATH']
  %w[1.8.6-p369 1.8.7-p334 1.9.2-p180].each do |ruby_ver|
    ruby_path = "/usr/local/ruby/#{ruby_ver}/bin"
    ENV['PATH'] = ruby_path + ':' + orig_path
    puts "*** ruby_path=#{ruby_path}"
    sh "ruby -v"
    _do_test()
  end
end


def copy_into(*args)
  args = args.flatten
  dir = args.pop
  mkdir_p dir unless File.exists?(dir)
  cp_r args, dir
end


def edit_files(*filenames, &block)
  filenames.flatten.each do |fname|
    Dir.glob(fname).each do |fpath|
      next unless File.file?(fpath)
      s = File.open(fpath, 'rb') {|f| f.read() }
      s = block.arity == 2 ? yield(s, fpath) : yield(s)
      File.open(fpath, 'wb') {|f| f.write(s) }
    end
  end
end


desc "create 'build/#{project}-#{release}/' and copy files to it"
task :build do
  dir = "build/#{project}-#{release}"
  #rm_rf dir if File.exist?(dir)
  fnames = Dir.glob("#{dir}*")
  rm_rf fnames unless fnames.empty?
  mkdir_p dir
  ## store
  cp_r %W[README.txt CHANGES.txt Rakefile #{project}.gemspec setup.rb], dir
  copy_into Dir.glob("lib/*.rb"),      "#{dir}/lib"
  copy_into Dir.glob("test/*test.rb"), "#{dir}/test"
  copy_into Dir.glob("examples/*.rb"), "#{dir}/examples"
  ## edit
  edit_files("#{dir}/**/*") do |content, filename|
    if ! %w[Rakefile setup.rb oktest.rb].include?(File.basename(filename))
      content.gsub! /\$Release:.*?\$/,   "$Release: #{release} $"
      content.gsub! /\$Copyright:.*?\$/, "$Copyright: #{copyright} $"
      content.gsub! /\$License:.*?\$/,   "$License: #{license} $"
      content.gsub! /\$Release\$/,   release
      content.gsub! /\$Copyright\$/, copyright
      content.gsub! /\$License\$/,   license
    end
    content
  end
end


desc "create *.tar.gz and *.gem packages"
task :packages => :build do
  base = "#{project}-#{release}"
  chdir "build" do
    sh "tar cf #{base}.tar.gz #{base}"
  end
  chdir "build/#{base}" do
    sh "gem build #{project}.gemspec"
    mv Dir.glob("#{project}-*.gem"), ".."
  end
end


desc "copy 'oktest.rb' into 'test/'"
task :oktest => "test/oktest.rb"

file "test/oktest.rb" => File.expand_path("~/src/oktest/ruby/lib/oktest.rb") do |t|
  cp t.prerequisites, "test"
end

#task "availables" do |t|
#  methods = t.methods.sort - Object.new.methods
#  $stderr.puts "\033[0;31m*** debug: methods=#{methods.inspect}\033[0m"
#end
